@baseUrl = http://localhost:5089
@email = test.user@example.com
@password = ChangeMe123!
@email2 = test.user2@example.com
@token1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZWFiZDU1ZS05ZTcyLTRmYjctYjY0MS1kMTkyNTczZTFkODgiLCJlbWFpbCI6InRlc3QudXNlckBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkVtcGxveWVlIiwiZXhwIjoxNzkwODExMTYwLCJpc3MiOiJTaWduYWxSX0RlbW8iLCJhdWQiOiJTaWduYWxSX0RlbW8uQ2xpZW50In0.FEGtQb6vdQGU1V0V5tP-jV0S75EVD5DsejKK3AuIJLk
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWFhNDVlZS1hNjNmLTQ3NjgtYmQxMi1iYzkwZGYxOThjOWEiLCJlbWFpbCI6InRlc3QudXNlcjJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJFbXBsb3llZSIsImV4cCI6MTc5MDgwOTc2MiwiaXNzIjoiU2lnbmFsUl9EZW1vIiwiYXVkIjoiU2lnbmFsUl9EZW1vLkNsaWVudCJ9.q7rjtAv4pk7lBPJ5V1Li4BRCgc9R9BR7jhpzr5wVS8s
### Register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "{{email}}",
  "phoneNumber": "+15551234567",
  "password": "{{password}}"
}

### Register 2 
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "Test User 2",
  "email": "{{email2}}",
  "phoneNumber": "+15551234567",
  "password": "{{password}}"
}
### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login2
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "{{email2}}",
  "password": "{{password}}"
}

### get chats for messages test
# @name getChatsForMessages
GET {{baseUrl}}/api/chats
Authorization: Bearer {{token1}}

### get messages from the first chat
GET {{baseUrl}}/api/chats/{{getChatsForMessages.response.body.$[0].chatId}}/messages?page=1&size=10
Authorization: Bearer {{token1}}

### get chats
GET {{baseUrl}}/api/chats
Authorization: Bearer {{token2}}